USE ragnarok
source C:/users/jeff/projects/ro/eathena/sql-files/item_db.sql
source C:/users/jeff/projects/ro/eathena/sql-files/item_db2.sql
source C:/users/jeff/projects/ro/eathena/sql-files/logs.sql
source C:/users/jeff/projects/ro/eathena/sql-files/main.sql
source C:/users/jeff/projects/ro/eathena/sql-files/mob_db.sql
source C:/users/jeff/projects/ro/eathena/sql-files/mob_db2.sql
source C:/users/jeff/projects/ro/eathena/sql-files/sqibonus.sql
source C:/users/jeff/projects/ro/eathena/sql-files/register.sql